name: Hardware Test Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm

    steps:
      - uses: actions/checkout@v4

      - name: Install and update packages
        run: |
          apt-get update
          apt-get -y install python3 python3-pip python3-venv p7zip-full libarchive13
          python3 --version
          python3 -m venv venv
          . ./venv/bin/activate
          python3 -m pip install --upgrade pip setuptools

      - name: Compile tests
        run: |
          make -C tests/AppCpuTimeLimit
          make -C tests/DetectEmulator
          make -C tests/HelloWorldSVC
          make -C tests/ImmediateModeTriangles
          make -C tests/PICA_LITP
          make -C tests/SimplerTri

      - name: Clone and compile 3ds-examples
        run: |
          git clone --recursive https://github.com/devkitPro/3ds-examples tests/3ds-examples
          # The devkitpro docker image is outdated and cannot build 3ds-examples at the moment
          # TODO: Reenable this when it's updated again
          # make -C tests/3ds-examples

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: Source & Binaries
          path: tests
        
